version: '3.8'

services:
  db:
    image: postgres
    container_name: gate-guard-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres
    container_name: gate-guard-test-db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env.test
    volumes:
      - test_pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  test_pgdata:
